name: Build and Push Docker Image

on:
  push:
    branches: [ main ] # Or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Make sure this secret is set in repo settings
          password: ${{ secrets.DOCKER_PASSWORD }} # Make sure this secret is set in repo settings

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # Build context is the root of your repo (where Dockerfile is)
          push: true
          tags: jasong03/tvl_defillama:latest # IMPORTANT: Use your Docker Hub username and desired image name/tag
          # You can add more tags, e.g., using the commit SHA:
          # tags: |
          #   jasong03/tvl_defillama:latest
          #   jasong03/tvl_defillama:${{ github.sha }}
